### ISSUE TITLE
Отображение emoji в поле ввода сообщения и в списке контактов

### ISSUE THREAD

**Issue by AlisaGodina** [urfu-2017/team3#172]
Отображать emoji в поле ввода сообщения и в списке контактов в формате кода
http://prntscr.com/jj0zrt

**Comment by spt30** [comment]
пофиксим, если будет время
мы эту задачу примерно с апреля пытаемся решить
нет времени просто)
хотя нас за это меньше всего ебали
так что не сильно критично

**Comment by AlisaGodina** [comment]
Выглядит жутко стремно, пофиксить нужно обязательно

**Comment by spt30** [comment]
подумал, в список контактов можно и целый эмодзи влепить
