### ISSUE TITLE
Обрабатывать руты при помощи некста 

### ISSUE THREAD

**Issue by spt30** [urfu-2017/team3#19]
Next при изподкапотной сборке через webpack выдает просто страницу index.js, а остальные хочет, чтобы соответствовали рутам: например, по руту `/login` будет отрисовывать то, что лежит в файле `.pages/login`
Из этого вытекает 2 проблемы:

- мы не можем назвать файл так, как нам хочется
- мы не всегда хотим отдавать page, иногда (в частности, по `/login`), нужно редиректиться на другой сайт или тип того
- пока что все работает только через команду `node server`, а хотелось бы через next build, next start, чтобы webpack'ом все собиралось и мы кайфанули

Следовательно, хочется заставить его работать так, чтобы он по нашему руками прописанному руту переходил, куда нам надо. Декомпозиция выглядит следующим образом:

1. посмотреть в заметки Гоголева и Воронцова на Next.js (https://github.com/urfu-2017/notes-app-react)
2. посмотреть в руты паспорта и правильно выписать все функции и пути (https://github.com/urfu-2017/github-oauth-example)
3. посмотреть по ссылочке, которую я кидал в телегу про централизованный роутинг (https://github.com/zeit/next.js/wiki/Centralizing-Routing), можно также прочитать тут, чтобы с query еще разобраться (https://github.com/zeit/next.js#shallow-routing)
4. разобраться как работает разбиение на файлы с учетом всех вышеперечисленных штуковин, которые нам необходимы
5. **аккуратно смешать все это и сделать нормальный роутинг**

**Comment by Qoter** [comment]
Судя по всему этот issue можно закрывать, сошлись на использовании роутов из express
