### ISSUE TITLE
Ошибки при авторизации

### ISSUE THREAD

**Issue by Qoter** [urfu-2017/team3#25]
<img width="994" alt="2018-04-03 0 45 38" src="https://user-images.githubusercontent.com/13704520/38213211-dc3dc54e-36d9-11e8-806c-5506d674e6cd.png">
При авторизации проскакивает такая ошибка, воспроизводится локально.  

В проде тоже в логах есть эта ошибка [тыц](https://zeit.co/test3/test3/mswmqygkda/logs)

**Comment by ArtyMgn** [comment]
как оказалось, при попытке получить от базы пользователя иногда прилетает Not found
