### ISSUE TITLE
Предупреждение в production

### ISSUE THREAD

**Issue by Qoter** [urfu-2017/team3#26]
<img width="406" alt="2018-04-03 0 43 08" src="https://user-images.githubusercontent.com/13704520/38213261-0b28a428-36da-11e8-8749-e6c275aa9485.png">
При запуске в конфигурации 'production' выскакивает такое предупреждение.
Нужно разобраться, что это и починить, если это не гуд

**Comment by ArtyMgn** [comment]
![image](https://user-images.githubusercontent.com/21121427/38409013-31bfdbb2-3999-11e8-8747-e6d529ef5845.png)
Чтобы пофиксить, придется писать свой MemoryStore, который будет взаимодействовать с hrudb, или можно выбрать из предлагаемого [списка](https://github.com/expressjs/session/blob/master/README.md#compatible-session-stores) (но кажется, что нам это не подходит)
